### ISSUE TITLE
New version message pop-up triggers even if on latest version.

### ISSUE THREAD

**Issue by spankywetfish** [josch0/SDRunoPlugin_CloudMarkers#10]
I've update CM to the latest version (v0.4.0) via the zip download.
However when launching I receive the "There is an update" popup each time the plugin is loaded.

![cm-v0 4 0](https://user-images.githubusercontent.com/11835338/189479092-17701d9d-1fd0-4e06-af9c-d4d6fb7fc159.PNG)

On a slightly different note, do you have any tips for compiling in Visual Studio ?

**Comment by spankywetfish** [comment]
Ok, I can see in the code that this is due to the version check being against <https://cloudmarkers.josch0.dev/version.txt> which is still set to 0.3.0. So as soon as you update that file this issue should disappear. 

My other question still stands though, I've tried building the solution in VS but just get loads errors, be they about experimental filesystem removal or missing references in object files or a plethora of other issues, so any assistance would be appreciated.

**Comment by spankywetfish** [comment]
I can see that you have now updated the version.txt file with `0.4.0`, however the version popup persists, therefore the issue must be elsewhere. 


```
GET /version.txt HTTP/1.1
Accept: */*
Connection: close
Host: cloudmarkers.josch0.dev
User-Agent: cpp-httplib/0.7

HTTP/1.1 200 OK
Date: Mon, 12 Sep 2022 11:44:47 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade, close
Last-Modified: Sun, 11 Sep 2022 17:18:54 GMT
ETag: "6-5e869f93a79ad"
Accept-Ranges: bytes
Content-Length: 6
Vary: Accept-Encoding,User-Agent
Content-Type: text/plain

0.4.0
```

Looking at the code the version check appears to do a string comparison against the body output from the `/version.txt` page.
It looks like either there is a new-line/line-feed at the end of the version line in the file, or the webserver is adding one.
Either way the `\n` on the end of the output will likely be the cause of the strings not matching. So the solution is either to clean up the `version.txt` file, or add a step to the code to strip the excess `\n`


![cloudmarkers-ver-sniff](https://user-images.githubusercontent.com/11835338/189664700-cbe4d6db-3599-4b36-b032-4266b90009c4.PNG)

**Comment by josch0** [comment]
Hi!

Thanks for reporting. I have removed the \n from the version.txt file.
Can you check, if the popup is gone?

**Comment by josch0** [comment]
I wrote the plugin two years ago and had a lot of problems getting VS to work myself. I am not an experienced C++ developer and don't really know VS very well. I worked my way from error to error to even get the plugin to do what i want.

Then my notebook crashed and my entire development environment was gone. I have not yet tried again to get everything set up and running.

So I'm afraid I can't really help you. I remember there was a tutorial for plugin developers from SDRplay. And I asked around in the corresponding Facebook group. The .dll for version 0.4.0 was compiled by Andy from SDRplay, so the code itself should not be the problem.

**Comment by spankywetfish** [comment]
That fixed it, no more pop-up.  :¬)

I've manged to get the dll to compile, I think my main issue was I was compiling to x64 whereas I should have been aiming for x86.
That being said, my compiled version is 10 bytes smaller than the official dll and crashes when I load it, so I'm still doing something wrong. ¯\\\_(ツ)\_/¯

Unfortunately (or fortunately depending on how you look at it) I don't do Facebook, so wouldn't be able to check out the group.
