### ISSUE TITLE
missing Markers

### ISSUE THREAD

**Issue by glapics** [josch0/SDRunoPlugin_CloudMarkers#6]
markers how up  on the frequency display once the plugin is loaded but i have no ability to edit or add frequencies.
i have a empty " Markers " dialogue box, clicking on it  and nothing displays 
![cloudmarker](https://user-images.githubusercontent.com/99031793/152550804-e6753e92-5e44-4a08-83b2-d63807f9918a.jpg)

**Comment by gdienel** [comment]
I have the same problem, the way I got it to reappear was,
1. Hover over SDRUno Icon (When running) on the taskbar
2. Right click on the 'MARKERS' in the preview box, a context menu appears click on 'Move' (don't click any mouse buttons yet)
3. The mouse cursor moves to the top left of the screen with a move icon, I had to press the right arrow on the keyboard then without clicking mouse button drag the MARKERS window back into the centre on the desktop.
4. You should be able to now drag it to another position.
I am not sure why it exhibits this behaviour but I have to do this most times after launching SDRUno and trying to load the Markers plugin, but it works for me.
