### ISSUE TITLE
Cloud Marker Windows seems not to open

### ISSUE THREAD

**Issue by 914tom** [josch0/SDRunoPlugin_CloudMarkers#7]
when I start Cloud Marker the window doesn't open. 
If I then try to start the plugin again, the message appears that the plugin is already started. I suspect the window is outside the visible area of ​​my screen. Reinstalling and deleting the DB didn't work, Cloud Marker created a new DB but wont show up 
What can I do?

**Comment by MinimumFalcon** [comment]
Same problem here. I've reinstalled the plugin and it works once. Then, when I try to load it the next time, it remains minimized on the task bar, but blank. Great when it works. Frustrating.

**Comment by gdienel** [comment]
I posted something on another post with the same problem, a strange workaround, but worked for me but has to be done each startup (I have just copied from my other answer) :
1. Hover over SDRUno Icon (When running) on the taskbar
2. Right click on the 'MARKERS' in the preview box, a context menu appears click on 'Move' (don't click any mouse buttons yet)
3. The mouse cursor moves to the top left of the screen with a move icon, I had to press the right arrow on the keyboard then without clicking mouse button drag the MARKERS window back into the centre on the desktop.
4. You should be able to now drag it to another position.
I am not sure why it exhibits this behaviour but I have to do this most times after launching SDRUno and trying to load the Markers plugin, but it works for me.

I hope this helps others, I haven't been able to figure out why it does this.
